### ISSUE TITLE
fresh deployment failure

### ISSUE THREAD

**Issue by nexvisync** [nexvisync/Polytrix#1]
when user do a fresh git clone of the repository, after `npm install && bower install` on client app folder, `npm test` on server side folder would crash the app itself, please fix

**Comment by BrianSo** [comment]
Tried version [`71ca313` `1eb964c` `46aee5f`](https://github.com/nexvisync/Polytrix/commits/master). No error at all. I also tried on another PC, no problem at all. It should be your local computer problems.
